[project]
name = "langgraphTraining"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.62.0",
    "ipython>=9.10.0",
    "langchain-google-genai>=4.2.0",
    "langgraph>=1.0.8",
]
